include theme.conf
font_family      "JetBrainsMono Nerd Font"
font_size        11.0
background_opacity 0.95
window_padding_width 8

symbol_map U+E000-U+F8FF,U+F0000-U+FFFFD,U+100000-U+10FFFD Symbols Nerd Font Mono
