background            #0a0a0a
foreground            #e0e0e0
cursor                #00f0ff
cursor_text_color     background
selection_background  #0090a0
selection_foreground  #000000
url_color             #00f0ff

active_border_color    #00f0ff
inactive_border_color  #0090a0
bell_border_color      #ff3b3b

active_tab_foreground   #000000
active_tab_background   #00f0ff
inactive_tab_foreground #808080
inactive_tab_background #0a0a0a
tab_bar_background      #000000

color0  #0a0a0a
color1  #ff3b3b
color2  #00ff9c
color3  #ffd166
color4  #3ba7ff
color5  #c77dff
color6  #00f0ff
color7  #e0e0e0

color8  #808080
color9  #ff6b6b
color10 #5fffc0
color11 #fff09e
color12 #7cc0ff
color13 #e0b3ff
color14 #7dfbff
color15 #ffffff
